// "Against conventional wisdom" — the bet the substrate and the estate make. Everything under /thesis renders from this.

export const THESIS = {
  eyebrow: 'Against conventional wisdom',
  title: 'The competing bet.',
  lede:
    'The field agrees on the question — who authorized this agent, on whose behalf, and can it be verified? — and answers it with OAuth extensions, short-lived tokens, a registered issuer and a gateway. That answer is right for the organization that owns its resources and its liability, and we do not argue with it. Our bet is about the domains it cannot reach: where the person is the principal, the organizations are many and small or losing control of the relationship, and the records have to outlive every one of them. This page states the bet, names what it goes against, and says what would have to be true for it to win.',
  statement: [
    'Palantir could impose an ontology-first operating model because it pushed it into focused markets — government, defence, a handful of regulated industries — where one buyer could mandate the whole shape. Outside those boundaries the same discipline was judged too abstract and too expensive to adopt.',
    'AI removes the cost, not the disagreements. A model can read “a treasury is a service chartered under the principal whose money it holds” and apply it to a case without a team of ontologists in the room; it cannot decide what two organizations mean by “member.” The bet is that the cost was the barrier, and that shared meaning for authority — not for data — is where the disagreements must be settled once rather than translated at every act.',
    'Experts extrapolate their own stack: identity people extend the IdP, payments people extend the network, framework people extend the runtime. Each is right about its own ground. None of them is building the layer under all three, and the layer is now buildable by a small team on rented infrastructure.',
  ],
} as const;

export interface Architecture { name: string; root: string; authority: string; checked: string; evidence: string; goodAt: string; breaks: string }
export const ARCHITECTURES: readonly Architecture[] = [
  { name: 'Tenant', root: 'The organization’s IdP — Okta, Entra, Salesforce’s own permission model', authority: 'Tenant policy: roles, scopes, rich authorization details', checked: 'Inside the tenant’s services', evidence: 'The tenant’s logs', goodAt: 'One organization governing its own people, agents and resources, carrying liability it already carries', breaks: 'The moment the act crosses the tenant boundary' },
  { name: 'Federation', root: 'Each organization’s IdP recognizing selected others; a network in the middle for payments — Visa TAP, Mastercard Agent Pay; a vertical system of record — Salesforce, a church-management platform, an OTA', authority: 'Tenant policy plus issuer trust; the intermediary’s rules for what crosses', checked: 'At each resource owner, against issuers it trusts; at the intermediary', evidence: 'Each party’s logs; the intermediary’s records', goodAt: 'Many organizations that already trust a common intermediary and can afford the integration', breaks: 'Domains without an intermediary; domains where the intermediary’s terms are the problem; the person’s records, which belong to no tenant' },
  { name: 'Substrate', root: 'The principal’s own account; a chain no single party in the domain operates', authority: 'A signed, caveated, revocable grant the principal issued; a mandate per consequential act', checked: 'Per step in the harness; at commit on chain for value; at admission by every resource owner', evidence: 'The owner’s vault; digests anchored on chain', goodAt: 'Many parties, no common intermediary or one losing control, the person as the paying principal, records that outlive any organization', breaks: 'Resources the principal does not own — every one of them still admits on its own terms; effects the chain does not order' },
];

export interface DomainBet { domain: string; intermediary: string; principal: string; outlive: string; fit: string; bet: string; mustBeTrue: string }
export const DOMAINS: readonly DomainBet[] = [
  { domain: 'Enterprise workflow', intermediary: 'The tenant itself', principal: 'The organization', outlive: 'No', fit: 'Not ours. The tenant model wins its own ground and should.', bet: 'None. We do not sell against Okta or Entra inside a tenant.', mustBeTrue: '—' },
  { domain: 'Faith communities, mission work, mutual care', intermediary: 'None. Many small organizations, none large enough to be the root; church-management SaaS holds each one’s slice', principal: 'The person, mostly', outlive: 'Yes — giving, formation, relationships and safety-sensitive records follow a person across congregations, agencies and decades', fit: 'The first beachhead. The only column where the substrate’s claims are not already someone else’s product.', bet: 'A person-centric record and a person-issued grant beat “each organization’s system of record plus its agent,” because the person belongs to several organizations and the organizations cannot afford to be roots.', mustBeTrue: 'Two separately governed organizations complete real work under it — an invitation, a payment, a migration — and prefer it to the church-management platform they have.' },
  { domain: 'Travel', intermediary: 'Today: card networks, GDSs, OTAs. Tomorrow, on this bet: fewer of them', principal: 'The traveller', outlive: 'Yes, on this bet — the itinerary, the preferences, the loyalty and the receipts are the traveller’s, not an airline’s order record', fit: 'The second beachhead: the disintermediation bet.', bet: 'Providers want the direct relationship with the consumer and are winning it; OTAs and GDSs lose control of the order as that happens; the airlines’ own answer — “One Order,” NDC — is a tenant move that keeps the order inside the carrier. The traveller’s agent, carrying the traveller’s itinerary and issuing mandates to providers it engages directly, is the shape that serves both the consumer and the provider once the intermediary is gone. Payment still clears through a network; the network is a settlement rail under the mandate, not the root of the traveller’s authority.', mustBeTrue: 'Providers accept a traveller-issued mandate at admission in preference to an intermediary’s token, because it brings them the direct relationship and the receipt. A traveller carries one itinerary across an airline, a hotel and a ground operator with no OTA holding the master record. The card network clears a mandate-bound payment without needing to be the authority.' },
  { domain: 'Healthcare, education', intermediary: 'Regulators and large institutions', principal: 'Mixed', outlive: 'Yes, by law', fit: 'Later, through regulation-driven portability. Not a beachhead.', bet: 'Portability mandates will want a record the person carries, and a substrate that already has one.', mustBeTrue: 'A regulator names an owner-held, verifiable record as an acceptable form.' },
];

export interface Bet { id: string; claim: string; because: string; against: string }
export const BETS: readonly Bet[] = [
  { id: 'ontology', claim: 'Shared meaning for authority is worth its cost, even where data can be translated.', because: 'AI makes mapping between local schemas cheap — the counter-hypothesis is probably right for read-only integration. It is wrong for authority: a mandate over “a payment to a member” must mean the same thing to the payer’s verifier and the payee’s, and translation at act time is where injection lives. One vocabulary from intent to receipt is what makes a mandate typeable.', against: 'Ship a schema and a prompt; let the model translate.' },
  { id: 'identity', claim: 'A principal is an account that can sign and delegate — with no central identity provider — and the same principal under a different behaviour definition is a different agent for trust.', because: 'An ERC-7710 delegation needs a delegator a stranger can check at redemption; a pointer cannot be that. Principal continuity is not behaviour continuity: every receipt cites the playbook digest, and a counterparty’s trust edges are keyed on the pair.', against: 'The IdP is the root of agent identity.' },
  { id: 'projection', claim: 'Identity is not the registry. Discovery ≠ willingness ≠ authority; resolution is not authority.', because: 'A registry can list and delist. It cannot revoke a grant it never issued. A resolver returns addresses, never credentials. Registry and discovery become the SEO of the agentic web — worth doing well, never the root.', against: 'Register the agent; the registry is the trust anchor.' },
  { id: 'private', claim: 'The private surface is the identity plus a vault the person custodies — and each principal’s vault holds its own side of a shared record.', because: 'Records that would be a bereavement if lost live in the owner’s vault, ontology-shaped and portable to another Home. An organization is a principal with a vault of its own; nothing is one party’s alone if two signed it. Safety-sensitive relationships are vault credentials, not chain records.', against: 'The application’s database is the record; the user gets an export.' },
  { id: 'public', claim: 'The public surface holds only what any chain read reproduces — commitments, names, types, capability definitions — never the relationship graph of a population that needs to be discreet.', because: 'A public knowledge base that is a pure projection of the chain can be queried by a generated query safely. Membership and stewardship in the target domain are not public facts; on chain they are digests, in vaults they are records.', against: 'One vector store with row-level ACLs, queried by the model.' },
  { id: 'kit', claim: 'A very large, composable agentic kit is now feasible on rented infrastructure — and code volume is not the moat.', because: 'Seventy-seven packages and fifty contracts on Workers, Durable Objects and a chain, exercised nightly. AI makes the same kit cheaper for competitors too. What accumulates is the estate, the ontology’s governance and the trust edges, not the lines.', against: 'Buy nine products and integrate at the seams.' },
  { id: 'rails', claim: 'Guardrails are rails, not throttles — and every seam the chain does not order is receipted.', because: 'A throttle bounds rate, reach or confidence inside one vendor. A rail is a refusal outside the proposer: admission, custody, authority, mandate, the risk ladder, enforcement at commit for value, revocation. There is a seam at every effect the chain does not order; the receipt names which end committed it and what it observed.', against: 'Sandbox it, supervise it, put a second model in front of it.' },
  { id: 'trust', claim: 'Trust is relational — between two parties, for an intent, in a context — and no score is published at the index. The reader may compute one.', because: 'Provenance and trust need an ontology and a trust graph: signed edges returned separately. A relying party that ranks candidates from relevant edges, independent verification and cost is doing what the principle asks. The prohibition is on a mandatory global number from nobody’s vantage point.', against: 'A reputation number at the index.' },
  { id: 'intent', claim: 'One intent flow sits behind every interface. Click, chat, voice → typed intent → mandate.', because: 'The button and the sentence are two entrances to one feature: the same rules, the same checks, the same receipt. A button with explicit parameters needs no model interpretation; chat may need clarification; reads and drafts need no ceremony at all.', against: 'Build the feature, then teach the assistant about it separately.' },
  { id: 'digest', claim: 'Consequential effects bind to a closed mandate — the digest of one typed intent, a single-use nonce, the resource pinned. Open intents are caveated delegations that decompose into closed mandates as they become concrete.', because: 'When a person states an open intent they do not yet know which resources it will need. Hashing it binds the approved object, not the actions that satisfy it; something must check that each proposed effect conforms to the stated outcome, and each consequential effect gets its own signature. AP2’s intent and cart mandates are the same split; what we add is enforcement at commit and the owner’s receipt.', against: 'payments:write, and a policy table at every resource server.' },
  { id: 'home', claim: 'The Home is the only place a credential is used. Applications request ceremonies — and a Home is replaceable.', because: 'An app never sees a passkey, a key or a session secret; it asks the Home for a ceremony and receives a session and a signed grant. A Home concentrates power, so moving between Homes must be a rotation ceremony that preserves grants, never a recovery.', against: 'Every app integrates the IdP and stores a token.' },
  { id: 'delegate', claim: 'The application is a delegate, never a custodian — and every resource owner still admits.', because: '“No held key” is not the property; “not the custodian” is. A service that acts as an agent holds a narrow, revocable delegation to its own session key. A principal can delegate only what it has: the resource owner verifies the grants it chooses to recognize. There is no central authorization server; there are as many verifiers as resources.', against: 'The service account is the agent; the IdP decides.' },
  { id: 'coordination', claim: 'Coordination between principals is a different plane from orchestration inside one run, and the authority semantics sit above A2A and MCP, not in them. The agent survives its runtime.', because: 'Two A2A services can belong to one organization; an MCP call can cross one. The principal boundary is the grant, not the protocol. A handoff inside one process is orchestration; two custodians agreeing to act is coordination with its own plan, commitments and mandates.', against: 'Handoff is a state bag passed to another graph.' },
];

export const CONSENSUS = {
  lede: 'Everyone now agrees on the question. NIST NCCoE (February 2026), the OpenID Foundation’s AIIM working group — “who authorized this agent, on whose behalf, and can it be verified” — IETF WIMSE, the Cloud Security Alliance’s Agentic Trust Framework, three W3C community groups, Visa’s Trusted Agent Protocol and Mastercard Agent Pay. Every one answers with OAuth extensions, short-lived tokens, a registered issuer and a gateway.',
  idp: {
    line: 'The IdP world’s counter-hypothesis is “the IdP is the control plane.” Okta positions Cross App Access exactly there and announced Claude and VS Code integrations in June 2026. It is a serious bet, and inside a tenant it is the right one.',
    answers: ['Who is this user, workload, application or agent?', 'How was it authenticated?', 'What organization and groups does it belong to?', 'What applications may it access?', 'Under what conditions should access be allowed or revoked?'],
    strong: 'A control plane is where policy is defined and administrative decisions are made. The IdP is strong at admission and access for the people, workloads and agents an organization owns, and it carries the liability those decisions create. We do not compete with it there.',
    limit: 'Access alone does not express the authority of an act, and a tenant’s authority stops at the tenant. An IdP can say a principal may reach the payments service. It cannot say this payee, at most this amount, for this intent, once — checkable by a stranger, enforced at commit, revocable by the person rather than the tenant — and it cannot say anything at all about a person who belongs to three organizations and is a customer of a fourth. An IdP is an important admission authority. It is not the root of a person’s identity or of a person’s authority, and in the domains we build for, nothing centralized can be.',
  },
} as const;

export interface Principle { n: number; title: string; body: string; consequence?: string; changed?: string }
export const PRINCIPLES: readonly Principle[] = [
  { n: 1, title: 'Every concern has a private dimension and a public projection; the chain enforces value and projects claims.', body: 'A principal’s account is counterfactual: its address is computable from its custody configuration — a passkey, a social recovery set, a hardware key — and its signatures verify before it is ever deployed (ERC-6492). Identity, delegation and relationship are therefore defined, signed and verified off chain against that address, with no chain footprint. The chain enters for two reasons and on two ledgers: a private estate chain, validated by the domain’s own institutions, enforces value at commit and holds the private graph without exposure; a public chain carries the public projection — anchored receipts, admissions, reviews, provenance commitments, and set roots against which a stranger can verify membership or non-revocation without learning the graph.', consequence: 'For every other effect — a message, a vault write, a call to a provider — the chain is the ordering and revocation oracle, and the enforcement is the harness at one end and the resource owner’s admission at the other. There is a seam at every effect the chain does not order; the receipt names which end committed it. Neutral means the private chain is a consortium and the public projection is on ground nobody in the domain operates.' },
  { n: 2, title: 'The identity can sign; the behaviour is a separate claim.', body: 'Every principal — person, organization, service — is a smart account (ERC-4337): it verifies signatures about itself (ERC-1271), issues and revokes grants, holds value, executes logic, recovers by quorum. A name, a DID document, an NFT id, a SPIFFE id, a registry entry is a projection the anchor signs and can discard.', consequence: 'A principal keeps its address while its model, operator and playbook change. Every receipt cites the behaviour definition’s digest, and trust edges are keyed on principal and behaviour together. The cost — every principal needs an account, a custody policy and a paymaster — is paid for portability the person may never use, and is stated rather than hidden.' },
  { n: 3, title: 'Rotation preserves grants because the Home re-approves them; recovery revokes their descendants. Neither changes the identity.', body: 'Passkeys, hardware keys and KMS session keys are facets beneath the account under a custody policy. The contract’s invariant is strict and right: retiring any credential bumps the custody epoch, and every grant signed by that credential or approved under that epoch dies at redemption. Rotation — add a credential you control, retire one you still control — is therefore a ceremony that re-approves every standing wire under the new epoch in the same batch, so that from a counterparty’s vantage point nothing happened. Recovery — a credential you no longer control — bumps the epoch and re-approves nothing; every descendant of the compromised epoch is dead, and the person re-issues from a reviewed list.', consequence: 'Moving between Homes is a rotation, never a recovery. A leaked key is a recovery; the anchor, its names and its history are untouched. No application is a custodian: a service that acts as an agent holds a narrow delegation to its session key, never the identity’s key.' },
  { n: 4, title: 'A token is a claim that authority existed at issue time. A delegation is the authority itself, still checkable at act time.', body: 'Authority is a signed, caveated, attenuable, revocable artifact (ERC-7710) issued by the principal — no central authorization server. Caveats are executable: this payee, this ceiling, before this time, once. A delegate can only narrow. What federation cannot give is the first and last of these: principal-issued, and enforced at commit by code no party to the act operates.', consequence: 'A principal can delegate only what it has. Every resource owner remains the verifier of the grants it chooses to recognize; there are as many verifiers as resources, and the substrate is strongest where the resource is the principal’s own — its treasury, its vault, its agent.' },
  { n: 5, title: 'Consequential effects bind to one typed intent; open intents decompose.', body: 'A mandate is a delegation plus two caveats: the digest of one typed intent — payee, resource, amount, outcome — and a single-use nonce derived from a logical request identity. For payments the enforcer pins payee and ceiling. Confirmation is a passkey signature over that digest, and the act cannot commit without it. An open intent — “organize the retreat for under two thousand” — is a caveated delegation that bounds the envelope; each consequential effect inside it becomes its own closed mandate as it becomes concrete, and a conformance check compares each proposed effect against the stated outcome before it is offered for signature.', consequence: 'The planner may be creative about how; it cannot change what. AP2’s intent and cart mandates are the same split; the substrate adds enforcement at commit and the owner’s receipt.' },
  { n: 6, title: 'Verification lives outside the model, at every step, and at the end that commits — with a defined clock.', body: 'The grant is checked before each step and re-checked after every human approval. Then it depends on who orders the effect. Chain-ordered effects — value — are enforced by the mandate’s caveats inside the transaction that commits. Estate-ordered effects — a vault write, a message, another agent on the estate — are verified again by the receiver at the moment it executes, so there are two independent checks and the receiver’s is the one that counts. Externally ordered effects — a provider’s API — are verified once, and the receipt names the adapter that committed and what it observed; irreversible ones require a fresh signature. A revocation counts from inclusion on a chain with immediate finality and from finality elsewhere. An executor that cannot reach the chain stops. Aggregate limits are enforced at the resource, not the grant.', consequence: 'No protected act ever runs on a stored verdict. Revocation latency is a property of the network; never acting stale is a property of the design. There is a window between verification and an external provider’s commit; it is declared per tool, not denied.' },
  { n: 7, title: 'Accountability has three shapes, by doctrine.', body: 'PROV-O’s Person, Organization and SoftwareAgent, taken as the substrate’s convention: a team is an organization; a treasury is a service chartered under the organization whose money it holds; a steward authorizes and the treasury transacts under a mandate. For a person, the treasury is a facet of their own account with the same enforcers unless a reason requires otherwise.', consequence: 'charteredUnder, memberOf and stewardOf are never sufficient for permission. A policy may require current membership as one explicit condition; a verifier may never infer permission from a relationship.' },
  { n: 8, title: 'One vocabulary from utterance to audit; behaviour generated, authority never; versions bound.', body: 'Intent, capability, relationship, receipt and trust edge are IRIs in one ontology; code binds by IRI and a build gate fails on an invented term. Skills define an action once; the interface, the planner’s tools and the card are generated from it. A mandate binds the schema and execution-semantics version it was approved under, so a changed adapter cannot reinterpret an approved intent.', consequence: 'A playbook says how; it grants nothing. Four generated surfaces can agree about the wrong behaviour, so live gates with negative twins validate behaviour independently of the definition that generated it.' },
  { n: 9, title: 'Records belong to the owner; each principal holds its side; the app is a cache.', body: 'The test for any store: wiped, is it a rebuild or a bereavement? Bereavements live in the owner’s vault, ontology-shaped, per-record scoped, portable to another Home. An organization is a principal with a vault; a shared record has a side in each signer’s vault; a departing member keeps their receipts and not the organization’s records. A relationship has three forms: a vault credential each party holds and presents under grant; a record on the private estate chain where enforcement needs it; and, on the public chain, only a commitment — a set root or a membership proof — never the edge.', consequence: 'Two knowledge tiers never meet inside an engine: a public graph that holds only what any chain read reproduces, and a private vault read by selector under the asker’s grant. A generated query is never the reason something is disclosed, and a public chain read never reveals who belongs to what.' },
  { n: 10, title: 'Evidence travels with the owner, and its completeness is anchored.', body: 'Every protected act leaves a PROV receipt — tool, risk, mandate, verifier decision, approver signature, transaction hash, playbook digest — in the owner’s vault, recomputable without the runtime’s cooperation. Each receipt says which of four things it attests: attempted, accepted, state changed, outcome occurred. A run’s bundle digest is anchored on chain, so a verifier has an authoritative head and withholding is visible.', consequence: 'The runtime’s trace is the vendor’s; the receipt is the person’s. The behaviour definition is attested for identity; environment attestation is admitted as one more evidence edge, and the reader appraises.' },
  { n: 11, title: 'Trust is a graph; no score at the index; the reader computes.', body: 'No ranked list at the index beyond relevance, no index above the registries, no registry that can revoke a grant it never issued. Signed edges — member-of, attestation, verification receipt, interaction receipt, admission — are returned separately. A relying party may score, rank and shortlist from them; that is the principle, not an exception to it. Edges count against collusion only where they cost something — a payment that happened, an admission with a real bar, an attestation from a party with standing.', consequence: 'Resolution returns addresses, never credentials. Be what registries are built from. Canonical identities establish continuity, not independence; the graph is Sybil-resistant only through costly edges.' },
];

export const ACCUMULATES = [
  ['1 → 4', 'Neutral ground makes a delegation enforceable by strangers — for value at commit, for everything else by ordering and revocation.'],
  ['2 → 4', 'An identity that can sign makes a delegation issuable by the principal, with no central authorization server.'],
  ['3 → 2', 'Rotation that preserves grants and recovery that revokes descendants make the identity survive keys, vendors and Homes.'],
  ['5, 6 → 4', 'Closed mandates, conformance for open intents and per-step verification make a delegation safe in the hands of a planner that can be lied to.'],
  ['7, 8 → 5', 'Three accountable shapes and one vocabulary make an intent typeable — a mandate needs a typed intent, and the intent needs a world shape.'],
  ['9, 10', 'Owner-held records and anchored evidence make the whole thing accountable to the person, not the platform.'],
  ['11', 'A graph instead of a score at the index, and no root, keep it open.'],
  ['Estate', 'A Home, a runtime, an edge, a registry and a consortium chain make it usable — and two of them, separately governed, make it decentralized.'],
] as const;

export interface PeerHolding { peer: string; holds: string; note: string }
export const PEERS: readonly PeerHolding[] = [
  { peer: 'Okta · Entra', holds: '— (a weak 4)', note: 'Admission and access for what the tenant owns. Right inside a tenant; nothing to say about a person who belongs to three.' },
  { peer: 'Visa TAP · Mastercard Agent Pay', holds: '4’s envelope', note: 'Federation with a network as the intermediary. Owns card-cleared commerce today; a settlement rail under a mandate on our bet.' },
  { peer: 'Google AP2', holds: '5 (the open/closed split)', note: 'Intent and cart mandates as verifiable credentials with trusted approval surfaces. The closest precedent for principle 5; no enforcement at commit, no owner-held receipt.' },
  { peer: 'MetaMask DTK · Lit Vincent', holds: '1 · 2 · 4', note: 'The ERC-7710 object model and session UX, in more wallets than we reach. No harness discipline around it.' },
  { peer: 'Palantir', holds: '8', note: 'One ontology from data to decision — inside a tenant, for the customers who can mandate it.' },
  { peer: 'Dina · Hestia', holds: '9 · 10', note: 'Personal data stores, portability and owner-held records, with keys as identity.' },
  { peer: 'ERC-8004 · x402', holds: '1, and 11’s problem statement', note: 'On-chain identity registry and payments; the reputation registry is the score at the index, and the payment-backed-feedback work is drifting toward receipts.' },
  { peer: 'SAIHM', holds: '9’s container', note: 'A home for the agent’s state, without the grant model over it.' },
  { peer: 'W3C Agent Identity CG', holds: '2’s pointer', note: 'An identifier with a trust level — a pointer, not an account.' },
  { peer: 'Nobody', holds: '6 · 10 together', note: 'Verification outside the model at every step and at the end that commits, with evidence a counterparty can recompute against an anchored head. The combination is the perspective; the ordering is the argument.' },
];

export const EVIDENCE = [
  { k: 'Unfiltered averages fail, measured', v: 'A May 2026 study of ERC-8004 found roughly 170,000 registrations, Sybil-heavy, and 93.8% of reviewer addresses on Base with no measured payment history in the study window. That is the score at the index failing on schedule. It does not show that a canonical account resists Sybils — nothing does without costly edges — and we do not claim it does.' },
  { k: 'The identity half, from the inside', v: 'More than a fifth of the initial ERC-8004 agents were created by this project’s own testing. An NFT identity has no operating model built in — no signing, no delegation, no custody — and every serious use reached for ERC-4337 anyway. A registry trying to be the identity and the listing was neither well.' },
  { k: 'The receipt half, arriving', v: 'x402’s payment-backed-feedback proposal ties a review to a payment that happened — an interaction receipt, one edge of a trust graph, arriving from the other direction.' },
  { k: 'The disintermediation half, underway', v: 'Providers are winning direct relationships with consumers; the airlines’ “One Order” and NDC programmes are attempts to keep the order inside the carrier as the OTA and GDS lose it. Both moves take the record away from the intermediary. Neither gives it to the traveller. That gap is the travel bet.' },
  { k: 'The assumption underneath', v: 'Centralized registries that also try to be the canonical identity will not win, and intermediaries that own the person’s record will keep losing it. A registry should be built from the kit; the identity is the account; the record is the person’s.' },
] as const;

export const RISKS = [
  { risk: 'We are ahead on the axis enterprises are not yet buying.', mitigation: 'Do not sell to enterprises. The first beachhead is a domain with no intermediary — faith communities and mission work — where the person is the paying principal and the competitor is a church-management platform. Build to the domains beyond it that the substrate can scale into.' },
  { risk: 'The travel bet is a bet on disintermediation that the incumbents are fighting.', mitigation: 'Enter where the provider already wants the direct relationship — independent hotels, ground operators, the long tail carriers do not serve — and where the traveller already carries the itinerary. Treat the card network as a settlement rail under a mandate, not as the authority to displace. If providers keep choosing intermediary tokens over traveller mandates at admission, the bet is wrong and we will say so.' },
  { risk: 'A single-operator estate proves an integrated platform, not decentralization.', mitigation: 'Make the estate chain a consortium validated by the domain’s own institutions, and demonstrate two separately governed estates doing real work — the invitation, the payment, the migration, the compromise with descendants — under each other’s limits.' },
  { risk: 'The Home concentrates power, and passkeys are scoped to one relying party.', mitigation: 'Home-to-Home moves are rotation ceremonies that preserve grants; multi-credential custody policies are the default; a Home that cannot be left is a finding.' },
  { risk: 'The CSO will build from the IdP they already have.', mitigation: 'Let them, for their tenant. The estate is for the person the tenant does not own — the member, the traveller, the volunteer — and it federates with the tenant at admission rather than replacing it.' },
] as const;

export interface Dimension { concern: string; privateSide: string; enforcement: string; publicSide: string }
export const DIMENSIONS: readonly Dimension[] = [
  { concern: 'Custody', privateSide: 'A counterfactual account: the address follows from a passkey, a social recovery set or a hardware key; signatures verify before deployment (ERC-6492). Who custodies whom is a vault fact.', enforcement: 'Deployment and the custody policy on the private estate chain, when an act needs it; the custody epoch is what a counterparty reads.', publicSide: 'The address, its type and its capability definitions — never the custodians.' },
  { concern: 'Authority', privateSide: 'A delegation is a signed object held by the delegate and verified by signature against the delegator’s account, deployed or not. Off-chain validation is the default.', enforcement: 'Enforcers run at commit on the private chain for value; revocation is one read of isRevoked.', publicSide: 'A revocation root or a non-revocation proof, so a verifier outside the estate can check a grant without reading the estate’s chain.' },
  { concern: 'Admission', privateSide: 'The resource owner’s policy and the grants it recognizes, evaluated at its own edge.', enforcement: 'Admission receipts and the correlation id, minted at the edge; recorded privately.', publicSide: 'An admission commitment a registry can list; a registry’s signature binds only the fact of listing.' },
  { concern: 'Resolution', privateSide: 'Pairwise and private-with-audience service publications; opaque, recipient-bound discovery grants for unlisted agents.', enforcement: 'Sequenced, hash-chained, expiring publications the agent signs; a resolver selects, never edits.', publicSide: 'Public publications and typed names; addresses, never credentials.' },
  { concern: 'Relationships', privateSide: 'A vault credential each party holds — member-of, steward-of, chartered-under — presented under grant, read only from that party’s vantage point.', enforcement: 'The typed record on the private estate chain where a gate must follow it.', publicSide: 'A set root, an existence proof or a zero-knowledge membership proof; never the edge.' },
  { concern: 'Evidence', privateSide: 'The PROV receipt in the owner’s vault.', enforcement: 'The run’s bundle digest anchored, so completeness is provable and withholding visible.', publicSide: 'Anchored outcomes a stranger may see; reviews and interaction receipts as trust-graph edges.' },
];

export interface PrivacyTool { name: string; what: string; where: string }
export const PRIVACY_STACK: readonly PrivacyTool[] = [
  { name: 'Privacy Pools', what: 'An operational shielded pool with association sets: prove membership in a set of legitimate participants without revealing which one.', where: 'The shape of the public projection of a private graph — a set root a stranger verifies against, without learning the members. Also private value transfer for treasuries that must not be linkable.' },
  { name: 'Railgun', what: 'An open-source shielded system for using tokens and applications privately.', where: 'Private settlement where a mandate-bound payment must not expose payer, payee or amount on a public ledger.' },
  { name: 'Aztec', what: 'An Ethereum privacy layer with programmable private smart contracts and private state.', where: 'The only member of the stack that addresses graph privacy on a public chain: relationships and grants as private state with public proofs. Maturity is verified at adoption, not assumed.' },
  { name: 'Kohaku', what: 'An Ethereum Foundation wallet framework integrating Privacy Pools, Railgun, stealth addresses, private RPC access and relayers.', where: 'The Home’s wallet layer, so that a person’s public-chain projection — payments, anchors — is unlinkable by default.' },
];
