// "Against conventional wisdom" — the competing bet the substrate and the estate make, stated as bets, with the
// consensus it goes against named by name. Every page under /thesis renders from this.

export const THESIS = {
  eyebrow: 'Against conventional wisdom',
  title: 'The competing bet.',
  lede:
    'The field now agrees on the question — who authorized this agent, on whose behalf, and can it be verified? Every published answer is OAuth extensions, short-lived tokens, a registered issuer and a gateway: the architecture of 2012 with agents as clients. We are making a different bet. This page states it as a bet, names what it goes against, and says what would have to be true for it to win.',
  statement: [
    'Palantir could impose an ontology-first operating model because it pushed it into focused marketplaces — government, defence, a handful of regulated industries — where one buyer could mandate the whole shape. Outside those boundaries the same discipline was judged too abstract, too expensive to adopt, too far from how software is actually bought.',
    'AI removes the boundary. A model can read an abstract principle — “a treasury is a service chartered under the principal whose money it holds”, “a mandate binds to one typed intent” — and apply it to a concrete case without a team of ontologists in the room. The cost that kept core ontologies inside Palantir-shaped markets has collapsed, and the value has not.',
    'Experts have a hard time factoring in the power and impact of that collapse. Each specialty extrapolates its own stack: identity people extend the IdP, payments people extend the card network, framework people extend the runtime. The bet below is that the layer underneath all of them is now buildable, and that it accumulates.',
  ],
} as const;

export interface Bet { id: string; claim: string; because: string; against: string }
export const BETS: readonly Bet[] = [
  { id: 'ontology', claim: 'The value of core ontologies — protocol and domain — will exceed the field’s reluctance to adopt them.', because: 'AI lets abstract principles be applied by a model, not a committee. Abstraction is what gives a solution independence inside its own space: the same T-box binds the conversation, the harness, the card, the vault and the chain by IRI.', against: 'Ontologies are academic; ship a schema and a prompt.' },
  { id: 'identity', claim: 'Agent identity is a canonical account that can sign and delegate — separate from every registry projection — with no central identity provider.', because: 'Durable principalhood needs a thing that can verify signatures about itself, issue and revoke grants, hold value and be recovered by quorum. Only an account does all four. Names, cards, DID documents and registry entries are projections the account signs and can discard.', against: 'The IdP is the root of agent identity.' },
  { id: 'projection', claim: 'Identity is not the registry. Discovery ≠ willingness ≠ authority; resolution is not authority.', because: 'A registry can list and delist. It cannot revoke a grant it never issued. A resolver returns addresses, never credentials. Registry and discovery become the SEO of the agentic web — worth doing well, never the root.', against: 'Register the agent; the registry is the trust anchor.' },
  { id: 'private', claim: 'The private surface is the identity plus a vault the person custodies.', because: 'Records that would be a bereavement if lost — messages, grants, memory, receipts, relationships — live in the owner’s vault, ontology-shaped and portable to another Home. The application is a cache.', against: 'The application’s database is the record; the user gets an export.' },
  { id: 'public', claim: 'The public surface is reproducible from chain — a knowledge graph on a standard ontology, with ENS/DNS-style naming.', because: 'A public knowledge base that holds only what any chain read reproduces can be queried by a generated query safely: a wrong query costs a bad answer, never a disclosure. The two surfaces never meet inside an engine.', against: 'One vector store with row-level ACLs, queried by the model.' },
  { id: 'kit', claim: 'A very large, composable agentic kit — identity, authority, harness, edge, registry, evidence, coordination, ontology, operations — is now feasible on top of a serverless platform.', because: 'Seventy-seven packages and fifty contracts on Cloudflare Workers, Durable Objects and a chain, run by a small team, exercised nightly by live gates. The “OS platform” underneath is rented; the substrate on top is owned.', against: 'Buy nine products and integrate at the seams.' },
  { id: 'rails', claim: 'Guardrails are rails, not throttles — and there are no seams.', because: 'A throttle bounds rate, reach or confidence inside one vendor. A rail is a refusal that sits outside the proposer: admission, custody, authority, mandate, the risk ladder, enforcement at commit, revocation. One identity, one grant mechanism, one evidence trail, so there is no boundary at which a person becomes a token and the token becomes a row.', against: 'Sandbox it, supervise it, put a second model in front of it.' },
  { id: 'trust', claim: '“Trustless” means provenance drives trust. Trust is relational — between two parties, for an intent, in a context — never a score.', because: 'Provenance and trust need an ontology and a trust graph: PROV-O’s person, organization and software agent underneath, signed edges above, returned separately for the reader to compute. The score fails on schedule wherever it is tried.', against: 'A reputation number at the index.' },
  { id: 'intent', claim: 'One intent flow sits behind every interface. Click, chat, voice → typed intent → mandate.', because: 'The button and the sentence are two entrances to one feature: the same rules, the same checks, the same receipt. The definition is written once and the interfaces are generated from it.', against: 'Build the feature, then teach the assistant about it separately.' },
  { id: 'digest', claim: 'Authority binds to an intent digest, not a scope.', because: 'When a person states an intent they do not yet know which resources it will need, so the authority cannot be packaged as scopes or caveats up front. Bind the grant to the digest of the typed intent and a single-use nonce; the planner may be creative about how, and cannot change what.', against: 'payments:write, and a policy table at every resource server.' },
  { id: 'home', claim: 'The Home is the only place a credential is used. Applications request ceremonies.', because: 'An app never sees a passkey, a key or a session secret. It asks the Home for a ceremony — sign in, charter, grant, revoke — and receives a session and a signed delegation, nothing more.', against: 'Every app integrates the IdP and stores a token.' },
  { id: 'delegate', claim: 'The application is a delegate, never a custodian.', because: '“No held key” is not the property; “not the custodian” is. A service that acts as an agent holds a narrow, revocable delegation to its own session key. If its credentials leak, the attacker is a delegate only where a wire says so.', against: 'The service account is the agent.' },
  { id: 'coordination', claim: 'Agency and coordination between principals (A2A) are a different plane from orchestration and tooling inside one run (MCP). The agent survives its runtime.', because: 'A handoff inside one process is orchestration. Two custodians agreeing to act together is coordination, with its own plan, commitments and mandates. Conflate them and a runtime enrols people by iterating over them.', against: 'Handoff is a state bag passed to another graph.' },
];

export const CONSENSUS = {
  lede: 'Everyone now agrees on the question. NIST NCCoE (February 2026), the OpenID Foundation’s AIIM working group — “who authorized this agent, on whose behalf, and can it be verified” — IETF WIMSE, the Cloud Security Alliance’s Agentic Trust Framework, three W3C community groups, Visa’s Trusted Agent Protocol and Mastercard Agent Pay. Every one answers with OAuth extensions, short-lived tokens, a registered issuer and a gateway.',
  idp: {
    line: 'The IdP world’s counter-hypothesis is “the IdP is the control plane.” Okta shipped exactly that, inside Claude and VS Code, in June 2026. We name it as the competing bet, because it is a serious one.',
    answers: ['Who is this user, workload, application or agent?', 'How was it authenticated?', 'What organization and groups does it belong to?', 'What applications may it access?', 'Under what conditions should access be allowed or revoked?'],
    strong: 'A control plane is where policy is defined and administrative decisions are made. Traditionally the IdP controlled human access, and it is strong at exactly that: admission and access, for the workloads and people an organization owns.',
    limit: 'Access alone does not express the full authority of an action. An IdP can say a principal may reach the payments service. It cannot say this payee, at most this amount, for this intent, once — checkable by a stranger, enforced at commit, revocable by the person rather than the tenant. An IdP is an important admission authority. It cannot be the universal root of agent identity or of action authority, and there is no centralized authority that can.',
  },
} as const;

export interface Principle { n: number; title: string; body: string; consequence?: string }
export const PRINCIPLES: readonly Principle[] = [
  { n: 1, title: 'Neutral ground, or no ground.', body: 'The root of identity, permission and revocation is a public chain no vendor, IdP or platform operates.', consequence: 'A grant is checked by an enforcer contract at commit, in the same transaction as the act. The vendor consensus — “the IdP is the control plane” — is 2012 with agents as clients.' },
  { n: 2, title: 'The identity can sign.', body: 'Every principal — person, organization, service — is a smart account (ERC-4337): it verifies signatures about itself (ERC-1271), issues and revokes grants, holds value, executes logic, recovers by quorum.', consequence: 'A name, a DID document, an NFT id, a SPIFFE id, a registry entry is a pointer — a projection the anchor signs and can discard. Attach trust to a pointer and something else is the real identity, unnamed and unrevocable.' },
  { n: 3, title: 'Credentials rotate; the identity does not; no app is a custodian.', body: 'Passkeys, hardware keys and KMS session keys are facets beneath the account under a custody policy. A leaked key is a credential revocation, not a new agent; nothing that named the account must be re-signed.', consequence: 'A service that acts as an agent holds a narrow delegation to its session key, never the identity’s key. “No held key” is not the property; “not the custodian” is.' },
  { n: 4, title: 'A token says who; a delegation says what.', body: 'Authority is a signed, caveated, attenuable, revocable artifact (ERC-7710) issued by the principal. There is no authorization server. Caveats are executable: this payee, this ceiling, before this time, once. A delegate can only narrow.', consequence: 'A token is a claim that authority existed at issue time. A delegation is the authority itself, checkable at act time.' },
  { n: 5, title: 'Authority binds to an intent, not a scope.', body: 'payments:write permits the wrong payee, the wrong amount and the same payment twice. A mandate is a delegation plus two caveats: the digest of one typed intent and a single-use nonce derived from it.', consequence: 'The planner may be creative about how; it cannot change what. Confirmation is a passkey signature over that digest, and the act cannot commit without it.' },
  { n: 6, title: 'Verification lives outside the model, at every step, and again at commit.', body: 'Intelligence may be probabilistic; authority must not be. The grant is checked before each step, re-checked after every human approval (the world moved while it waited), and enforced on chain when value moves.', consequence: 'No protected act ever runs on a stored verdict. Revocation latency is a property of the network; never acting stale is a property of the design.' },
  { n: 7, title: 'Accountability has exactly three shapes.', body: 'PROV-O’s trichotomy as law: Person, Organization, SoftwareAgent. A team is an organization; a treasury is a service chartered under the principal whose money it holds; a person never pays — they authorize, and the treasury transacts under a mandate.', consequence: 'charteredUnder, memberOf and stewardOf are relationships a resolver may follow and a verifier may never read as permission.' },
  { n: 8, title: 'One vocabulary from utterance to audit; behaviour generated, authority never.', body: 'Intent, capability, relationship, receipt and trust edge are IRIs in one ontology; code binds by IRI and a build gate fails on an invented term. Skills define an action once; from that definition the UI, the tool the planner sees and the card other agents read are all generated.', consequence: 'Domain shape never lives in a prompt, a SKILL.md or a lookup table. A playbook says how; it grants nothing.' },
  { n: 9, title: 'Records belong to the owner; the app is a cache.', body: 'The test for any store: wiped, is it a rebuild or a bereavement? Bereavements — messages, grants, memory, receipts, skills, relationships — live in the owner’s vault, ontology-shaped, per-record scoped, portable to another Home.', consequence: 'Two knowledge tiers never meet inside an engine: a public graph that holds only what any chain read reproduces, and a private vault read by selector under the asker’s grant. A generated query is never the reason something is disclosed.' },
  { n: 10, title: 'Evidence travels with the owner.', body: 'Every protected act leaves a PROV receipt — tool, risk, mandate, verifier decision, approver signature, transaction hash, playbook digest — in the owner’s vault, recomputable without the runtime’s cooperation.', consequence: 'The runtime’s trace is the vendor’s; the receipt is the person’s. What is attested is the behaviour definition, never the binary.' },
  { n: 11, title: 'Trust is a graph; discovery is not authority; nobody is the root.', body: 'No score, no ranked list, no index above the registries, no registry that can revoke a grant it never issued. Signed edges — member-of, attestation, verification receipt, interaction receipt, admission — are returned separately; the reader computes.', consequence: 'Resolution returns addresses, never credentials. Be what registries are built from. ERC-8004’s own 2026 empirics — 170k identities, Sybil-heavy, 94% of reviewers never paid — are the scalar failing on schedule.' },
];

export const ACCUMULATES = [
  ['1 → 4', 'Neutral ground makes a delegation enforceable by strangers.'],
  ['2 → 4', 'An identity that can sign makes a delegation issuable by the principal, with no authorization server.'],
  ['3 → 2', 'Custody beneath the account makes the identity survive keys, vendors and hosts.'],
  ['5, 6 → 4', 'Intent binding and per-step verification make a delegation safe in the hands of a planner that can be lied to.'],
  ['7, 8 → 5', 'Three accountable shapes and one vocabulary make an intent typeable — a mandate needs a typed intent, and the intent needs a world shape.'],
  ['9, 10', 'Owner-held records and owner-held evidence make the whole thing accountable to the person, not the platform.'],
  ['11', 'A graph instead of a score, and no root, keep it open.'],
  ['Home', 'The estate — a Home, a runtime, an edge, a registry, a chain — makes it usable.'],
] as const;

export interface PeerHolding { peer: string; holds: string; note: string }
export const PEERS: readonly PeerHolding[] = [
  { peer: 'Okta · Entra', holds: '— (a weak 4)', note: 'Admission and access for what the tenant owns; no neutral ground, no identity that signs, scopes rather than caveats.' },
  { peer: 'MetaMask DTK · Lit Vincent', holds: '1 · 2 · 4', note: 'The ERC-7710 object model and session UX, in more wallets than we reach. No harness discipline around it.' },
  { peer: 'Palantir', holds: '8', note: 'One ontology from data to decision — inside a tenant, for the customers who can mandate it.' },
  { peer: 'Dina · Hestia', holds: '9', note: 'Personal data stores and portability, with keys as identity.' },
  { peer: 'ERC-8004 · x402', holds: '1, and 11’s problem statement', note: 'On-chain identity registry and payments; the reputation registry is the score, and the payment-backed-feedback work is drifting toward receipts.' },
  { peer: 'SAIHM', holds: '9’s container', note: 'A home for the agent’s state, without the grant model over it.' },
  { peer: 'W3C Agent Identity CG', holds: '2’s pointer', note: 'An identifier with a trust level — a pointer, not an account.' },
  { peer: 'Nobody', holds: '5 · 6 · 10', note: 'Intent-digest binding, verification outside the model at every step and at commit, evidence recomputable without the runtime. The combination is the perspective; the ordering is the argument.' },
];

export const EVIDENCE = [
  { k: 'The score half, measured', v: 'ERC-8004’s May 2026 empirics: roughly 170,000 registrations, Sybil-heavy, and 93.8% of reviewers on Base had never paid for anything they reviewed. The scalar fails exactly as predicted, at scale, in public.' },
  { k: 'The identity half, from the inside', v: 'More than a fifth of the initial ERC-8004 agents were created by this project’s own testing. What that exercise showed: an NFT identity has no operating model built in — no signing, no delegation, no custody — and every serious use had to reach for ERC-4337 anyway. The registry was trying to be both the identity and the listing, and could be neither well.' },
  { k: 'The receipt half, arriving', v: 'x402’s payment-backed-feedback proposal ties a review to a payment that actually happened. That is an interaction receipt — one edge of a trust graph — arriving from the other direction.' },
  { k: 'The assumption underneath', v: 'Centralized registries that also try to be the canonical identity will not win. A registry should be built from the kit; the identity is the account.' },
] as const;

export const RISKS = [
  { risk: 'We are ahead on the axis enterprises are not yet buying.', mitigation: 'Find a focused industry or domain where a beachhead can be made — one buyer, one operating model, the Palantir move — while building to the larger markets the substrate can scale into. Faith-community organizations and mission field work are the first estate for that reason.' },
  { risk: 'The CSO is going to build from the IdP they already have.', mitigation: 'Build the estate as a bounded, private deployment of decentralized principles — its own chain, its own Home, its own edge — so an organization gets the substrate’s properties without exposing itself to a public network. Decentralized inside the estate boundary first; federated across estates when the ceremonies are proven.' },
] as const;
